apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - name      : postgres-mlflow
      protocol  : TCP
      targetPort: 5432  # Port on POD
      nodePort  : 32321  # Port on Load Balancer
      port      : 3239
  selector:
    app: postgres